/**
 * 그트플 통합관리시스템 - 기초정보 코드 정의
 * 24종 코드 체계 데이터 기반 정의
 */

const CODE_DEFINITIONS = {

    // ===== 1. 마스터상품 코드 (GTP) =====
    master_product: {
        name: '마스터상품',
        prefix: 'GTP',
        description: '모든 상품의 기본 단위. SKU상품, 매핑, 시세조회 등 전체 시스템의 근간',
        icon: '📦',
        hasMasterDashboard: true,
        hasUnitSystem: true,
        hasAutoTranslate: false,
        fieldSections: [
            { title: '기본정보', fields: ['master_product_id','product_name_kr','category_large','category_medium','category_small','origin','purchase_channel','storage_type','storage_zone','supplier_id'] },
            { title: '단위코드 관리', fields: ['unit_system_placeholder'] },
            { title: '보관/관리 정보', fields: ['min_stock_days','avg_stock_days','max_stock_days','daily_optimal_qty','kamis_code','haccp_required'] },
            { title: '담당자 정보', fields: ['inbound_manager','inventory_manager','packaging_manager'] },
            { title: 'SKU 매핑', fields: ['mapping_actions'] },
            { title: '기타', fields: ['status','remarks','change_history_btn'] },
        ],
        fields: [
            // ── 기본정보 ──
            { key: 'master_product_id', label: '마스터상품코드', type: 'text', required: true, auto: true, width: 140, hint: '상품명 초성 기반 자동부여 (GTP-[초성그룹]-순번)' },
            { key: 'product_name_kr', label: '상품명(한국어)', type: 'text', required: true, width: 150 },
            { key: 'product_name_kh', label: '상품명(캄보디아어)', type: 'text', required: false, width: 150, hint: '한국어 등록시 자동 번역' },
            { key: 'category_large', label: '대분류', type: 'select', required: false, width: 100,
              options: ['엽채류','과채류','근채류','과일류','양념채소','버섯류','기타'] },
            { key: 'category_medium', label: '중분류', type: 'select', required: false, width: 100,
              options: ['쌈채소','샐러드','양념채소','열매채소','뿌리채소','기타'], editable: true },
            { key: 'category_small', label: '소분류', type: 'text', required: false, width: 100 },
            { key: 'origin', label: '원산지', type: 'select', required: false, width: 80,
              options: ['국산','수입(중국)','수입(미국)','수입(베트남)','수입(기타)'] },
            { key: 'purchase_channel', label: '매입채널', type: 'select', required: false, width: 80,
              options: ['농장','시장','외부'] },
            { key: 'storage_type', label: '보관구분', type: 'select', required: false, width: 80,
              options: ['냉장','냉동','상온'] },
            { key: 'storage_zone', label: '보관존', type: 'select', required: false, width: 100,
              options: ['A존','B존','C존','D존','기타'] },
            { key: 'supplier_id', label: '매입거래처', type: 'ref_select', refCode: 'supplier', refNameField: 'supplier_name', refIdField: 'supplier_id', required: false, width: 120 },

            // ── 단위코드 (실제 데이터 저장용, 폼에서는 unit_system으로 렌더링) ──
            { key: 'use_unit_kg',      label: 'kg단위 사용', type: 'hidden', required: false },
            { key: 'weight_unit_kg',   label: 'kg단위 중량(kg)', type: 'hidden', required: false },
            { key: 'use_unit_box',     label: '박스단위 사용', type: 'hidden', required: false },
            { key: 'weight_unit_box',  label: '박스단위 중량(kg)', type: 'hidden', required: false },
            { key: 'use_unit_pack',    label: '팩단위 사용', type: 'hidden', required: false },
            { key: 'weight_unit_pack', label: '팩단위 중량(kg)', type: 'hidden', required: false },
            { key: 'use_unit_tonbag',  label: '톤백단위 사용', type: 'hidden', required: false },
            { key: 'weight_unit_tonbag',label: '톤백단위 중량(kg)', type: 'hidden', required: false },
            { key: 'use_unit_pallet',  label: '파레트단위 사용', type: 'hidden', required: false },
            { key: 'weight_unit_pallet',label: '파레트단위 중량(kg)', type: 'hidden', required: false },

            // 단위시스템 플레이스홀더 (폼에서 커스텀 렌더링)
            { key: 'unit_system_placeholder', label: '단위 선택', type: 'unit_system', required: false },

            // ── 보관/관리 정보 ──
            { key: 'min_stock_days', label: '최소보관일', type: 'number', required: false, width: 80 },
            { key: 'avg_stock_days', label: '평균보관일', type: 'number', required: false, width: 80 },
            { key: 'max_stock_days', label: '최대보관일', type: 'number', required: false, width: 80 },
            { key: 'daily_optimal_qty', label: '1일 적정보유량', type: 'number', required: false, width: 100 },
            { key: 'kamis_code', label: 'KAMIS 연동코드', type: 'text', required: false, width: 110 },
            { key: 'haccp_required', label: 'HACCP 대상', type: 'select', required: false, width: 90,
              options: ['Y','N'] },

            // ── 담당자 (복수 선택, 알림 연동 예정) ──
            { key: 'inbound_manager', label: '입고관리 담당자', type: 'multi_ref', refCode: 'employee', refNameField: 'employee_name_kr', refIdField: 'employee_id', required: false, width: 120, hint: '복수 선택 가능. 입고 알림 전송 대상' },
            { key: 'inventory_manager', label: '재고관리 담당자', type: 'multi_ref', refCode: 'employee', refNameField: 'employee_name_kr', refIdField: 'employee_id', required: false, width: 120, hint: '복수 선택 가능. 재고 알림 전송 대상' },
            { key: 'packaging_manager', label: '포장작업 담당자', type: 'multi_ref', refCode: 'employee', refNameField: 'employee_name_kr', refIdField: 'employee_id', required: false, width: 120, hint: '복수 선택 가능. 출고 알림 전송 대상' },

            // ── 매핑 액션 (버튼용 플레이스홀더) ──
            { key: 'mapping_actions', label: 'SKU 매핑', type: 'mapping_actions', required: false },

            // ── 기타 ──
            { key: 'status', label: '사용상태', type: 'select', required: false, width: 80,
              options: ['사용','정지','삭제'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
            { key: 'change_history_btn', label: '변경이력', type: 'change_history', required: false },
        ],
        listColumns: ['master_product_id','product_name_kr','category_large','origin','purchase_channel','storage_type','status'],
    },

    // ===== 2. SKU상품 코드 =====
    sku_product: {
        name: 'SKU상품',
        prefix: 'SKU',
        description: '판매처별 SKU코드 관리. 혼합상품, 증정상품, 포장정보, 중량 자동계산 지원',
        icon: '🏷️',
        hasSkuMasterItems: true,
        hasChangeHistory: true,
        fieldSections: [
            { title: '기본정보', fields: ['sku_id','sku_name','sku_seller_id'] },
            { title: '혼합상품 / 마스터상품 연결', fields: ['is_mixed','mixed_count','sku_master_items_placeholder'] },
            { title: '증정상품', fields: ['has_gift','gift_count','sku_gift_items_placeholder'] },
            { title: '배송/출고 정보', fields: ['delivery_category','logistics_vehicle','outbound_deadline','own_or_consign','consign_supplier_id','outbound_zone'] },
            { title: '운영정보', fields: ['daily_avg_outbound','daily_max_production','order_deadline'] },
            { title: '기타', fields: ['registered_stores','status','remarks','change_history_btn'] },
        ],
        fields: [
            // ── 기본정보 ──
            { key: 'sku_id', label: 'SKU상품 코드', type: 'text', required: true, width: 130, hint: '판매처 SKU코드 직접입력' },
            { key: 'sku_name', label: 'SKU상품명', type: 'text', required: true, width: 200 },
            { key: 'sku_seller_id', label: 'SKU판매처 코드', type: 'ref_select', refCode: 'seller', refNameField: 'seller_name', refIdField: 'seller_id', required: false, width: 120 },

            // ── 혼합상품 / 마스터상품 연결 ──
            { key: 'is_mixed', label: '혼합상품 여부', type: 'select', required: true, width: 100,
              options: ['단독','혼합'], default: '단독', hint: '단독: 1개 상품, 혼합: 여러 마스터상품' },
            { key: 'mixed_count', label: '혼합상품 개수', type: 'number', required: false, width: 80, hint: '혼합 선택시 상품 개수 입력' },
            { key: 'master_items_json', label: '마스터상품 연결정보', type: 'hidden', required: false },
            { key: 'sku_master_items_placeholder', label: '마스터상품 상세', type: 'sku_master_items', required: false },

            // ── 증정상품 ──
            { key: 'has_gift', label: '증정상품 여부', type: 'select', required: false, width: 90,
              options: ['N','Y'], default: 'N' },
            { key: 'gift_count', label: '증정상품 개수', type: 'number', required: false, width: 80, hint: '증정상품 개수 입력' },
            { key: 'gift_items_json', label: '증정상품 연결정보', type: 'hidden', required: false },
            { key: 'sku_gift_items_placeholder', label: '증정상품 상세', type: 'sku_gift_items', required: false },

            // ── 배송/출고 정보 ──
            { key: 'delivery_category', label: '배송구분', type: 'select', required: false, width: 100,
              options: ['자체배송','택배','화물','퀵'] },
            { key: 'logistics_vehicle', label: '물류차량', type: 'ref_select', refCode: 'logistics', refNameField: 'vehicle_name', refIdField: 'logistics_id', required: false, width: 120 },
            { key: 'outbound_deadline', label: '출고마감(시간)', type: 'time', required: false, width: 100 },
            { key: 'own_or_consign', label: '직영위탁', type: 'select', required: false, width: 80,
              options: ['직영','위탁'] },
            { key: 'consign_supplier_id', label: '위탁매입처', type: 'ref_select', refCode: 'supplier', refNameField: 'supplier_name', refIdField: 'supplier_id', required: false, width: 120 },
            { key: 'outbound_zone', label: '출고생산존', type: 'select', required: false, width: 100,
              options: ['A존','B존','C존','D존','기타'] },

            // ── 운영정보 ──
            { key: 'daily_avg_outbound', label: '1일 출고량(평균)', type: 'number', required: false, width: 100 },
            { key: 'daily_max_production', label: '1일 최대생산량', type: 'number', required: false, width: 100 },
            { key: 'order_deadline', label: '주문마감(시간)', type: 'time', required: false, width: 100 },

            // ── 기타 ──
            { key: 'registered_stores', label: '등록스토어', type: 'text', required: false, width: 150 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','삭제'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
            { key: 'change_history_btn', label: '변경이력', type: 'change_history', required: false },
        ],
        listColumns: ['sku_id','sku_name','sku_seller_id','is_mixed','delivery_category','own_or_consign','outbound_zone','status'],
        excelBulk: true,
    },

    // ===== 3. 마스터-SKU 매핑 =====
    product_mapping: {
        name: '마스터-SKU 매핑',
        prefix: 'MAP',
        description: '마스터상품과 SKU상품의 연결 관계 관리. 미매핑 SKU 알림 지원',
        icon: '🔗',
        fields: [
            { key: 'mapping_id', label: '매핑 코드', type: 'text', required: true, auto: true, width: 110 },
            { key: 'master_product_id', label: '마스터상품 코드', type: 'ref', refCode: 'master_product', required: true, width: 120 },
            { key: 'sku_id', label: 'SKU상품 코드', type: 'ref', refCode: 'sku_product', required: true, width: 120 },
            { key: 'conversion_rate', label: '환산비율', type: 'number', required: true, width: 90, hint: '마스터 1kg 기준 SKU 수량' },
            { key: 'mapping_weight_g', label: '매핑 출고중량(g)', type: 'number', required: false, width: 110, hint: '혼합상품 시 해당 상품 중량' },
            { key: 'priority', label: '우선순위', type: 'number', required: false, width: 80 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지'], default: '사용' },
        ],
        listColumns: ['mapping_id','master_product_id','sku_id','conversion_rate','mapping_weight_g','priority','status'],
    },

    // ===== 4. 포장자재 코드 =====
    package_material: {
        name: '포장자재',
        prefix: 'PKG',
        description: '포장자재 관리. 현황 대시보드, 테이블형 재고현황표 지원',
        icon: '📋',
        hasInventoryView: true,
        fields: [
            { key: 'package_id', label: '포장자재 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'package_name', label: '포장자재명', type: 'text', required: true, width: 150 },
            { key: 'category', label: '자재분류', type: 'select', required: true, width: 100,
              options: ['포장팩','박스','라벨지','테이프','완충재','밴드','기타'], editable: true },
            { key: 'specification', label: '규격', type: 'text', required: false, width: 120 },
            { key: 'unit', label: '단위', type: 'select', required: true, width: 60,
              options: ['개','롤','장','박스','세트'] },
            { key: 'unit_price', label: '단가', type: 'number', required: false, width: 80 },
            { key: 'supplier_id', label: '주거래처', type: 'ref', refCode: 'supplier', required: false, width: 110 },
            { key: 'current_stock', label: '현재고', type: 'number', required: false, width: 80 },
            { key: 'min_stock_qty', label: '최소재고량', type: 'number', required: false, width: 90 },
            { key: 'max_stock_qty', label: '최대재고량', type: 'number', required: false, width: 90 },
            { key: 'storage_location', label: '보관위치', type: 'text', required: false, width: 100 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','삭제'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['package_id','package_name','category','specification','unit','unit_price','current_stock','min_stock_qty','status'],
    },

    // ===== 5. 소모품 코드 =====
    consumable: {
        name: '소모품',
        prefix: 'CSM',
        description: '사무용품, 탕비비품, 기타 소모성 자재. 현황 대시보드, 테이블형 재고현황표',
        icon: '🧴',
        hasInventoryView: true,
        fields: [
            { key: 'consumable_id', label: '소모품 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'consumable_name', label: '소모품명', type: 'text', required: true, width: 150 },
            { key: 'category', label: '소모품분류', type: 'select', required: true, width: 100,
              options: ['사무용품','탕비비품','청소용품','위생용품','기타'], editable: true },
            { key: 'specification', label: '규격', type: 'text', required: false, width: 120 },
            { key: 'unit', label: '단위', type: 'select', required: true, width: 60,
              options: ['개','박스','팩','롤','병','세트'] },
            { key: 'unit_price', label: '단가', type: 'number', required: false, width: 80 },
            { key: 'supplier_id', label: '주거래처', type: 'ref', refCode: 'supplier', required: false, width: 110 },
            { key: 'current_stock', label: '현재고', type: 'number', required: false, width: 80 },
            { key: 'min_stock_qty', label: '최소재고량', type: 'number', required: false, width: 90 },
            { key: 'storage_location', label: '보관위치', type: 'text', required: false, width: 100 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','삭제'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['consumable_id','consumable_name','category','unit','unit_price','current_stock','min_stock_qty','status'],
    },

    // ===== 6. 물류자재 코드 =====
    logistics_material: {
        name: '물류자재',
        prefix: 'EQP',
        description: '바구니, 파레트 등 반복사용 물류자재. 렌탈 자재 포함. 현황 대시보드',
        icon: '🧰',
        hasInventoryView: true,
        fields: [
            { key: 'equipment_id', label: '물류자재 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'equipment_name', label: '물류자재명', type: 'text', required: true, width: 150 },
            { key: 'category', label: '자재분류', type: 'select', required: true, width: 100,
              options: ['바구니','파레트','진열대','운반카트','기타'], editable: true },
            { key: 'specification', label: '규격', type: 'text', required: false, width: 120 },
            { key: 'unit', label: '단위', type: 'select', required: true, width: 60,
              options: ['개','대','세트'] },
            { key: 'quantity', label: '보유수량', type: 'number', required: false, width: 80 },
            { key: 'ownership_type', label: '소유구분', type: 'select', required: true, width: 80,
              options: ['자체','렌탈'], default: '자체' },
            { key: 'daily_rental_cost', label: '1일 렌탈비', type: 'number', required: false, width: 90, hint: '렌탈자재만 입력' },
            { key: 'unit_price', label: '단가(취득가)', type: 'number', required: false, width: 90 },
            { key: 'purchase_date', label: '취득일', type: 'date', required: false, width: 100 },
            { key: 'supplier_id', label: '거래처', type: 'ref', refCode: 'supplier', required: false, width: 110 },
            { key: 'storage_location', label: '보관위치', type: 'text', required: false, width: 100 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','폐기'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['equipment_id','equipment_name','category','quantity','ownership_type','daily_rental_cost','unit_price','status'],
    },

    // ===== 7. 시설/기구 코드 =====
    facility: {
        name: '시설/기구',
        prefix: 'FCL',
        description: '농장 및 사무실 시설, 기구 자산 관리',
        icon: '🏗️',
        fields: [
            { key: 'facility_id', label: '시설/기구 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'facility_name', label: '시설/기구명', type: 'text', required: true, width: 150 },
            { key: 'category', label: '분류', type: 'select', required: true, width: 80,
              options: ['시설','기구'] },
            { key: 'specification', label: '규격/모델', type: 'text', required: false, width: 120 },
            { key: 'location', label: '설치위치', type: 'text', required: false, width: 120 },
            { key: 'purchase_date', label: '취득일', type: 'date', required: false, width: 100 },
            { key: 'purchase_price', label: '취득가', type: 'number', required: false, width: 100 },
            { key: 'depreciation_years', label: '감가상각(년)', type: 'number', required: false, width: 90 },
            { key: 'supplier_id', label: '거래처', type: 'ref', refCode: 'supplier', required: false, width: 110 },
            { key: 'maintenance_cycle', label: '유지보수 주기', type: 'select', required: false, width: 100,
              options: ['월','분기','반기','연'] },
            { key: 'last_maintenance', label: '최근 유지보수일', type: 'date', required: false, width: 110 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','폐기'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['facility_id','facility_name','category','location','purchase_price','depreciation_years','status'],
    },

    // ===== 8. 매출거래처 코드 =====
    customer: {
        name: '매출거래처',
        prefix: 'CST',
        description: '판매채널(GTP-오프라인, CHEF-온라인), 판매처, 입고센터 3단계 구조',
        icon: '🏢',
        fields: [
            { key: 'customer_id', label: '매출거래처 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'customer_name', label: '거래처명', type: 'text', required: true, width: 150 },
            { key: 'sales_channel', label: '판매채널', type: 'select', required: true, width: 110,
              options: ['GTP-오프라인','CHEF-온라인'] },
            { key: 'channel_detail', label: '채널상세', type: 'text', required: false, width: 120 },
            { key: 'business_number', label: '사업자번호', type: 'text', required: false, width: 120 },
            { key: 'representative', label: '대표자명', type: 'text', required: false, width: 100 },
            { key: 'contact_person', label: '담당자명', type: 'text', required: false, width: 100 },
            { key: 'phone', label: '연락처', type: 'text', required: false, width: 120 },
            { key: 'email', label: '이메일', type: 'text', required: false, width: 150 },
            { key: 'address', label: '주소', type: 'text', required: false, width: 200 },
            { key: 'commission_rate', label: '수수료율(%)', type: 'number', required: false, width: 90 },
            { key: 'payment_terms', label: '결제조건', type: 'select', required: false, width: 90,
              options: ['선불','후불','월정산','기타'] },
            { key: 'contract_start', label: '계약시작일', type: 'date', required: false, width: 100 },
            { key: 'contract_end', label: '계약종료일', type: 'date', required: false, width: 100 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','삭제'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['customer_id','customer_name','sales_channel','channel_detail','commission_rate','payment_terms','status'],
    },

    // ===== 9. 매입거래처 코드 =====
    supplier: {
        name: '매입거래처',
        prefix: 'SUP',
        description: '상품/자재/소모품/물류 매입처 통합 관리',
        icon: '🚚',
        fields: [
            { key: 'supplier_id', label: '매입거래처 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'supplier_name', label: '거래처명', type: 'text', required: true, width: 150 },
            { key: 'supplier_type', label: '거래처 구분', type: 'select', required: true, width: 100,
              options: ['상품매입','자재매입','소모품매입','물류'] },
            { key: 'business_number', label: '사업자번호', type: 'text', required: false, width: 120 },
            { key: 'representative', label: '대표자명', type: 'text', required: false, width: 100 },
            { key: 'contact_person', label: '담당자명', type: 'text', required: false, width: 100 },
            { key: 'phone', label: '연락처', type: 'text', required: false, width: 120 },
            { key: 'email', label: '이메일', type: 'text', required: false, width: 150 },
            { key: 'address', label: '주소', type: 'text', required: false, width: 200 },
            { key: 'bank_name', label: '은행명', type: 'text', required: false, width: 80 },
            { key: 'bank_account', label: '계좌번호', type: 'text', required: false, width: 130 },
            { key: 'account_holder', label: '예금주', type: 'text', required: false, width: 80 },
            { key: 'payment_terms', label: '결제조건', type: 'select', required: false, width: 90,
              options: ['현금','외상','월정산','기타'] },
            { key: 'lead_time_days', label: '납품소요일', type: 'number', required: false, width: 80 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','삭제'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['supplier_id','supplier_name','supplier_type','contact_person','phone','payment_terms','status'],
    },

    // ===== 10. 역발행 거래처 코드 =====
    reverse_invoice: {
        name: '역발행 거래처',
        prefix: 'RIV',
        description: '판매처에서 수수료 계산서를 역발행하는 거래처',
        icon: '📄',
        fields: [
            { key: 'reverse_id', label: '역발행 거래처 코드', type: 'text', required: true, auto: true, width: 130 },
            { key: 'customer_id', label: '매출거래처 코드', type: 'ref', refCode: 'customer', required: true, width: 120 },
            { key: 'business_number', label: '사업자번호', type: 'text', required: true, width: 120 },
            { key: 'company_name', label: '상호', type: 'text', required: true, width: 150 },
            { key: 'representative', label: '대표자명', type: 'text', required: false, width: 100 },
            { key: 'invoice_type', label: '발행유형', type: 'select', required: true, width: 100,
              options: ['수수료','장려금','판촉비','기타'] },
            { key: 'commission_rate', label: '수수료율(%)', type: 'number', required: false, width: 90 },
            { key: 'billing_cycle', label: '정산주기', type: 'select', required: false, width: 80,
              options: ['월','분기','반기','연'] },
            { key: 'contact_person', label: '담당자명', type: 'text', required: false, width: 100 },
            { key: 'phone', label: '연락처', type: 'text', required: false, width: 120 },
            { key: 'email', label: '이메일', type: 'text', required: false, width: 150 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','삭제'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['reverse_id','company_name','customer_id','invoice_type','commission_rate','billing_cycle','status'],
    },

    // ===== 11. 부서/팀 코드 =====
    department: {
        name: '부서/팀',
        prefix: 'DPT',
        description: '조직 구조 관리',
        icon: '🏛️',
        fields: [
            { key: 'dept_id', label: '부서/팀 코드', type: 'text', required: true, auto: true, width: 110 },
            { key: 'dept_name', label: '부서/팀명', type: 'text', required: true, width: 120 },
            { key: 'dept_type', label: '구분', type: 'select', required: true, width: 70,
              options: ['부서','팀'] },
            { key: 'parent_dept_id', label: '상위부서', type: 'ref', refCode: 'department', required: false, width: 110 },
            { key: 'dept_head_id', label: '부서장', type: 'ref', refCode: 'employee', required: false, width: 110 },
            { key: 'sort_order', label: '정렬순서', type: 'number', required: false, width: 80 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['dept_id','dept_name','dept_type','parent_dept_id','dept_head_id','sort_order','status'],
    },

    // ===== 12. 직원 코드 =====
    employee: {
        name: '직원',
        prefix: 'EMP',
        description: '전체 직원 정보. 한국인 관리자 + 캄보디아 현장직원',
        icon: '👤',
        fields: [
            { key: 'employee_id', label: '직원 코드', type: 'text', required: true, auto: true, width: 110 },
            { key: 'employee_name_kr', label: '이름(한국어)', type: 'text', required: true, width: 100 },
            { key: 'employee_name_kh', label: '이름(캄보디아어)', type: 'text', required: false, width: 120 },
            { key: 'dept_id', label: '소속부서', type: 'ref', refCode: 'department', required: true, width: 110 },
            { key: 'position', label: '직위/직급', type: 'text', required: false, width: 90 },
            { key: 'employee_type', label: '직원구분', type: 'select', required: true, width: 80,
              options: ['관리직','현장직','계약직'] },
            { key: 'nationality', label: '국적', type: 'select', required: true, width: 80,
              options: ['한국','캄보디아','기타'] },
            { key: 'phone', label: '연락처', type: 'text', required: false, width: 120 },
            { key: 'email', label: '이메일', type: 'text', required: false, width: 150 },
            { key: 'hire_date', label: '입사일', type: 'date', required: true, width: 100 },
            { key: 'resign_date', label: '퇴사일', type: 'date', required: false, width: 100 },
            { key: 'hourly_wage', label: '시급', type: 'number', required: false, width: 80 },
            { key: 'monthly_salary', label: '월급', type: 'number', required: false, width: 100 },
            { key: 'annual_leave', label: '연차일수', type: 'number', required: false, width: 80 },
            { key: 'status', label: '재직상태', type: 'select', required: true, width: 80,
              options: ['재직','휴직','퇴직'], default: '재직' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['employee_id','employee_name_kr','dept_id','employee_type','nationality','hire_date','status'],
    },

    // ===== 13. 사용자계정 코드 =====
    user_account: {
        name: '사용자계정',
        prefix: 'USR',
        description: '시스템 로그인 계정. 직원코드와 연동, 권한그룹 설정',
        icon: '🔑',
        fields: [
            { key: 'user_id', label: '사용자계정 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'employee_id', label: '직원 코드', type: 'ref', refCode: 'employee', required: true, width: 110 },
            { key: 'login_id', label: '로그인 ID', type: 'text', required: true, width: 120 },
            { key: 'password', label: '비밀번호', type: 'password', required: true, width: 120 },
            { key: 'auth_group', label: '권한그룹', type: 'select', required: true, width: 100,
              options: ['경영그룹','사용자그룹','농장그룹','물류현장그룹','거래처그룹'] },
            { key: 'language', label: '언어설정', type: 'select', required: true, width: 90,
              options: ['KR','KH'], default: 'KR' },
            { key: 'status', label: '계정상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','잠금'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['user_id','employee_id','login_id','auth_group','language','status'],
    },

    // ===== 14. 재배하우스 코드 (하우스 정보 업데이트) =====
    greenhouse: {
        name: '하우스 정보 업데이트',
        prefix: 'GHS',
        description: '농장 하우스 개별 관리. 파종→생육→수확 자동계산, 수확량 추적, 손익 분석',
        icon: '🌿',
        hasHarvestCalc: true,
        fieldSections: [
            { title: '하우스 기본정보', fields: ['greenhouse_id','greenhouse_name','house_status','location','area_pyeong','usage_type','base_crop_period'] },
            { title: '작물 재배정보', fields: ['crop_id','variety_info','variety_code','sowing_date','growth_period','harvest_period','harvest_start_date','harvest_end_date','daily_harvest_target','total_harvest_target'] },
            { title: '수확 실적 (추후 개발)', fields: ['harvest_notice'] },
            { title: '하우스 추가정보', fields: ['acquisition_type','usage_period_years','purchase_price','annual_rent','depreciation_years','initial_facility_invest','additional_facility_invest','repair_info','ownership_type'] },
            { title: '기타', fields: ['status','remarks'] },
        ],
        fields: [
            // ── 하우스 기본정보 ──
            { key: 'greenhouse_id', label: '하우스코드', type: 'text', required: true, auto: true, width: 110 },
            { key: 'greenhouse_name', label: '하우스명', type: 'text', required: true, width: 100 },
            { key: 'house_status', label: '상태', type: 'select', required: true, width: 80,
              options: ['휴경중','생육중','수확중','정비중','보수중'], default: '휴경중' },
            { key: 'location', label: '위치', type: 'text', required: false, width: 120 },
            { key: 'area_pyeong', label: '면적(평)', type: 'number', required: false, width: 80 },
            { key: 'usage_type', label: '용도', type: 'select', required: true, width: 80,
              options: ['생산동','육묘동','관리동','창고동'], default: '생산동' },
            { key: 'base_crop_period', label: '기본작기(일)', type: 'number', required: false, width: 90, default: '45', hint: '기본 45일, 변경시 수확예상량 자동반영' },

            // ── 작물 재배정보 ──
            { key: 'crop_id', label: '작물등록', type: 'ref', refCode: 'master_product', required: false, width: 120, hint: '마스터코드 또는 상품명으로 조회' },
            { key: 'variety_info', label: '품종정보', type: 'text', required: false, width: 120, hint: '예) 빌모린블루락' },
            { key: 'variety_code', label: '품종코드', type: 'text', required: false, width: 100, hint: '신규생성 가능' },
            { key: 'sowing_date', label: '파종일자', type: 'date', required: false, width: 100 },
            { key: 'growth_period', label: '생육기간(일)', type: 'number', required: false, width: 90, default: '45', hint: '변경시 수확시작일 자동계산' },
            { key: 'harvest_period', label: '수확기간(일)', type: 'number', required: false, width: 90, default: '10', hint: '변경시 수확종료일 자동계산' },
            { key: 'harvest_start_date', label: '수확시작일', type: 'date', required: false, width: 100, computed: true, hint: '파종일 + 생육기간 자동계산' },
            { key: 'harvest_end_date', label: '수확종료일', type: 'date', required: false, width: 100, computed: true, hint: '수확시작일 + 수확기간 자동계산' },
            { key: 'daily_harvest_target', label: '1일 수확목표(kg)', type: 'number', required: false, width: 110 },
            { key: 'total_harvest_target', label: '전체 수확목표(kg)', type: 'number', required: false, width: 110, hint: '1일목표 x 수확기간 자동계산 가능' },

            // ── 수확 실적 (추후 개발) ──
            { key: 'harvest_notice', label: '수확현황', type: 'notice', required: false, width: 200,
              noticeText: '수확량 입력: 날짜별 수확량(kg) 입력 방식으로 추후 개발\n수확현황 조회: 하우스별 수확현황 확인 화면 추후 개발' },

            // ── 하우스 추가정보 ──
            { key: 'acquisition_type', label: '취득형태', type: 'select', required: false, width: 80,
              options: ['임대','자가'] },
            { key: 'usage_period_years', label: '사용기간(년)', type: 'number', required: false, width: 90, hint: '임대시 계약기간' },
            { key: 'purchase_price', label: '취득가', type: 'number', required: false, width: 100 },
            { key: 'annual_rent', label: '임대료(년)', type: 'number', required: false, width: 100, hint: '임대시 입력' },
            { key: 'depreciation_years', label: '감가상각(년)', type: 'number', required: false, width: 90 },
            { key: 'initial_facility_invest', label: '초기 시설투자', type: 'number', required: false, width: 100 },
            { key: 'additional_facility_invest', label: '추가 시설투자', type: 'number', required: false, width: 100 },
            { key: 'repair_info', label: '보수 정보', type: 'textarea', required: false, width: 200 },
            { key: 'ownership_type', label: '소유형태', type: 'select', required: false, width: 90,
              options: ['법인소유','개인소유'] },

            // ── 기타 ──
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','폐기'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['greenhouse_id','greenhouse_name','house_status','usage_type','area_pyeong','crop_id','sowing_date','harvest_start_date','total_harvest_target','status'],
    },

    // ===== 15. 설비 코드 =====
    farm_facility: {
        name: '설비',
        prefix: 'FAC',
        description: '하우스 내 설비(관수시설, 난방기, 환풍기 등)',
        icon: '⚙️',
        fields: [
            { key: 'farm_facility_id', label: '설비 코드', type: 'text', required: true, auto: true, width: 110 },
            { key: 'facility_name', label: '설비명', type: 'text', required: true, width: 150 },
            { key: 'category', label: '설비분류', type: 'select', required: true, width: 90,
              options: ['관수','난방','환기','조명','기타'] },
            { key: 'greenhouse_id', label: '설치 하우스', type: 'ref', refCode: 'greenhouse', required: false, width: 110 },
            { key: 'model', label: '모델명/규격', type: 'text', required: false, width: 120 },
            { key: 'purchase_date', label: '취득일', type: 'date', required: false, width: 100 },
            { key: 'purchase_price', label: '취득가', type: 'number', required: false, width: 90 },
            { key: 'maintenance_cycle', label: '유지보수 주기', type: 'select', required: false, width: 100,
              options: ['월','분기','반기','연'] },
            { key: 'last_maintenance', label: '최근 유지보수일', type: 'date', required: false, width: 110 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','폐기'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['farm_facility_id','facility_name','category','greenhouse_id','purchase_price','maintenance_cycle','status'],
    },

    // ===== 16. 농사장비 코드 =====
    agri_machine: {
        name: '농사장비',
        prefix: 'AGM',
        description: '트랙터, 경운기 등 농업용 기계장비',
        icon: '🚜',
        fields: [
            { key: 'agri_machine_id', label: '농사장비 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'machine_name', label: '장비명', type: 'text', required: true, width: 150 },
            { key: 'category', label: '장비분류', type: 'select', required: true, width: 90,
              options: ['경운기','트랙터','분무기','예초기','기타'], editable: true },
            { key: 'model', label: '모델명/규격', type: 'text', required: false, width: 120 },
            { key: 'purchase_date', label: '취득일', type: 'date', required: false, width: 100 },
            { key: 'purchase_price', label: '취득가', type: 'number', required: false, width: 90 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','폐기'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['agri_machine_id','machine_name','category','model','purchase_price','status'],
    },

    // ===== 17. 농사기구 코드 =====
    agri_tool: {
        name: '농사기구',
        prefix: 'AGT',
        description: '삽, 호미, 가위 등 소형 농기구',
        icon: '🔧',
        fields: [
            { key: 'agri_tool_id', label: '농사기구 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'tool_name', label: '기구명', type: 'text', required: true, width: 150 },
            { key: 'category', label: '기구분류', type: 'select', required: true, width: 90,
              options: ['수확용','정리용','관리용','기타'], editable: true },
            { key: 'quantity', label: '보유수량', type: 'number', required: false, width: 80 },
            { key: 'unit_price', label: '단가', type: 'number', required: false, width: 80 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','폐기'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['agri_tool_id','tool_name','category','quantity','unit_price','status'],
    },

    // ===== 18. 비용관리 코드 =====
    cost_code: {
        name: '비용관리',
        prefix: 'CSC',
        description: '전사 비용 입력 항목 코드. 모든 비용입력의 드롭다운 기준',
        icon: '💰',
        fields: [
            { key: 'cost_code_id', label: '비용관리 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'cost_name', label: '비용항목명', type: 'text', required: true, width: 150 },
            { key: 'cost_category', label: '비용대분류', type: 'select', required: true, width: 100,
              options: ['인건비','재료비','경비','감가상각','기타'], editable: true },
            { key: 'cost_subcategory', label: '비용중분류', type: 'text', required: false, width: 100 },
            { key: 'applicable_dept', label: '적용부서', type: 'select', required: false, width: 100,
              options: ['전체','농장','온라인','오프라인','물류','관리'] },
            { key: 'tax_type', label: '세금구분', type: 'select', required: false, width: 80,
              options: ['계산서','비계산서'] },
            { key: 'sort_order', label: '정렬순서', type: 'number', required: false, width: 80 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['cost_code_id','cost_name','cost_category','cost_subcategory','applicable_dept','tax_type','status'],
    },

    // ===== 19. 물류관리 코드 =====
    logistics: {
        name: '물류관리',
        prefix: 'LOG',
        description: '자체/외부 물류차량 등록 및 관리',
        icon: '🚛',
        fields: [
            { key: 'logistics_id', label: '물류관리 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'vehicle_name', label: '차량명/식별명', type: 'text', required: true, width: 120 },
            { key: 'vehicle_number', label: '차량번호', type: 'text', required: true, width: 100 },
            { key: 'vehicle_type', label: '차량유형', type: 'select', required: true, width: 90,
              options: ['냉장탑','화물','승합','기타'] },
            { key: 'ownership', label: '소유구분', type: 'select', required: true, width: 80,
              options: ['자체','외부'] },
            { key: 'supplier_id', label: '외부물류 거래처', type: 'ref', refCode: 'supplier', required: false, width: 120 },
            { key: 'insurance_start', label: '보험 시작일', type: 'date', required: false, width: 100 },
            { key: 'insurance_end', label: '보험 만료일', type: 'date', required: false, width: 100 },
            { key: 'insurance_cost', label: '보험료(원/년)', type: 'number', required: false, width: 100 },
            { key: 'driver_id', label: '담당기사', type: 'ref', refCode: 'employee', required: false, width: 110 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','폐기'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['logistics_id','vehicle_name','vehicle_number','vehicle_type','ownership','driver_id','status'],
    },

    // ===== 20. 배송타입 코드 =====
    delivery_type: {
        name: '배송타입',
        prefix: 'DLV',
        description: '배송 방식 구분. SKU상품, 주문, 출고에서 참조',
        icon: '📮',
        fields: [
            { key: 'delivery_type_id', label: '배송타입 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'delivery_type_name', label: '배송타입명', type: 'text', required: true, width: 120 },
            { key: 'delivery_method', label: '배송방법', type: 'select', required: true, width: 90,
              options: ['자체배송','택배','화물','퀵'] },
            { key: 'base_cost', label: '기본배송비', type: 'number', required: false, width: 90 },
            { key: 'free_shipping_amount', label: '무료배송 기준금액', type: 'number', required: false, width: 110 },
            { key: 'delivery_area', label: '배송지역', type: 'text', required: false, width: 120 },
            { key: 'sort_order', label: '정렬순서', type: 'number', required: false, width: 80 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['delivery_type_id','delivery_type_name','delivery_method','base_cost','free_shipping_amount','delivery_area','status'],
    },

    // ===== 21. 판매부서 코드 =====
    sales_dept: {
        name: '사업부서',
        prefix: 'SLD',
        description: '사업부서 등록. 사업부서별 판매채널, 판매처, 입고센터 관리의 최상위 단위',
        icon: '🏬',
        fields: [
            { key: 'sales_dept_id', label: '사업부서 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'sales_dept_name', label: '사업부서명', type: 'text', required: true, width: 150, hint: 'GTP-오프라인, CHEF-온라인 등' },
            { key: 'dept_head_id', label: '부서장', type: 'ref_select', refCode: 'employee', refNameField: 'employee_name_kr', refIdField: 'employee_id', required: false, width: 110 },
            { key: 'sort_order', label: '정렬순서', type: 'number', required: false, width: 80 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['sales_dept_id','sales_dept_name','dept_head_id','sort_order','status'],
    },

    // ===== 22. 판매채널 코드 =====
    sales_channel: {
        name: '판매채널',
        prefix: 'SCH',
        description: '사업부서 하위 판매채널 구분. 온라인채널, 오프라인채널, 기타채널 등',
        icon: '📡',
        fields: [
            { key: 'sales_channel_id', label: '판매채널 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'channel_name', label: '판매채널명', type: 'text', required: true, width: 150, hint: '온라인채널, 오프라인채널, 기타채널' },
            { key: 'sales_dept_id', label: '사업부서', type: 'ref_select', refCode: 'sales_dept', refNameField: 'sales_dept_name', refIdField: 'sales_dept_id', required: true, width: 120 },
            { key: 'channel_type', label: '채널유형', type: 'select', required: true, width: 90,
              options: ['온라인채널','오프라인채널','기타채널'] },
            { key: 'sort_order', label: '정렬순서', type: 'number', required: false, width: 80 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['sales_channel_id','channel_name','sales_dept_id','channel_type','status'],
    },

    // ===== 23. 판매처 코드 =====
    seller: {
        name: '판매처',
        prefix: 'SLR',
        description: '판매거래처 등록. 판매처별 주문집계, 손익관리 등',
        icon: '🛒',
        fields: [
            { key: 'seller_id', label: '판매처 코드', type: 'text', required: true, auto: true, width: 110 },
            { key: 'seller_name', label: '판매처명', type: 'text', required: true, width: 150 },
            { key: 'sales_dept_id', label: '사업부서', type: 'ref_select', refCode: 'sales_dept', refNameField: 'sales_dept_name', refIdField: 'sales_dept_id', required: true, width: 120 },
            { key: 'sales_channel_id', label: '판매채널', type: 'ref_select', refCode: 'sales_channel', refNameField: 'channel_name', refIdField: 'sales_channel_id', required: true, width: 120 },
            { key: 'platform_type', label: '플랫폼 유형', type: 'select', required: false, width: 100,
              options: ['오픈마켓','폐쇄몰','직거래','기타'] },
            { key: 'business_number', label: '사업자번호', type: 'text', required: false, width: 120 },
            { key: 'representative', label: '대표자명', type: 'text', required: false, width: 100 },
            { key: 'commission_rate', label: '수수료율(%)', type: 'number', required: false, width: 90 },
            { key: 'payment_terms', label: '결제조건', type: 'select', required: false, width: 90,
              options: ['선불','후불','월정산','기타'] },
            { key: 'settlement_cycle', label: '정산주기', type: 'select', required: false, width: 80,
              options: ['일','주','월'] },
            { key: 'contact_person', label: '담당자', type: 'text', required: false, width: 100 },
            { key: 'phone', label: '연락처', type: 'text', required: false, width: 120 },
            { key: 'email', label: '이메일', type: 'text', required: false, width: 150 },
            { key: 'address', label: '주소', type: 'text', required: false, width: 200 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','삭제'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['seller_id','seller_name','sales_dept_id','sales_channel_id','platform_type','commission_rate','payment_terms','status'],
    },

    // ===== 24. 판매처 입고센터 코드 =====
    receiving_center: {
        name: '판매처 입고센터',
        prefix: 'SLC',
        description: '판매처별 입고센터 등록. 입고센터별 주문집계, 손익관리 등',
        icon: '🏭',
        fields: [
            { key: 'center_id', label: '입고센터 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'center_name', label: '입고센터명', type: 'text', required: true, width: 150 },
            { key: 'seller_id', label: '판매처', type: 'ref_select', refCode: 'seller', refNameField: 'seller_name', refIdField: 'seller_id', required: true, width: 120 },
            { key: 'sales_dept_id', label: '사업부서', type: 'ref_select', refCode: 'sales_dept', refNameField: 'sales_dept_name', refIdField: 'sales_dept_id', required: false, width: 120, hint: '판매처 선택시 자동' },
            { key: 'address', label: '주소', type: 'text', required: true, width: 200 },
            { key: 'contact_person', label: '담당자', type: 'text', required: false, width: 100 },
            { key: 'phone', label: '연락처', type: 'text', required: false, width: 120 },
            { key: 'receiving_hours', label: '입고 가능시간', type: 'text', required: false, width: 120 },
            { key: 'delivery_type_id', label: '배송타입', type: 'ref_select', refCode: 'delivery_type', refNameField: 'delivery_type_name', refIdField: 'delivery_type_id', required: false, width: 100 },
            { key: 'special_requirements', label: '특이사항', type: 'textarea', required: false, width: 200 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지','삭제'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['center_id','center_name','seller_id','sales_dept_id','address','receiving_hours','status'],
    },

    // ===== 24. 3정5S 관리항목 코드 =====
    todo_item: {
        name: '3정5S 관리항목',
        prefix: 'TDO',
        description: 'TO DO LIST 관리 항목. 담당자 배정, 주기, 이행관리',
        icon: '✅',
        fields: [
            { key: 'todo_code_id', label: '관리항목 코드', type: 'text', required: true, auto: true, width: 120 },
            { key: 'todo_name_kr', label: '항목명(한국어)', type: 'text', required: true, width: 150 },
            { key: 'todo_name_kh', label: '항목명(캄보디아어)', type: 'text', required: false, width: 150 },
            { key: 'todo_category', label: '관리분류', type: 'select', required: true, width: 90,
              options: ['경영관리','현장관리','판매관리'] },
            { key: 'todo_subcategory', label: '세부분류', type: 'text', required: false, width: 120 },
            { key: 'management_cycle', label: '관리주기', type: 'select', required: true, width: 80,
              options: ['매일','주간','월간','분기','수시'] },
            { key: 'assigned_employee_id', label: '담당자', type: 'ref', refCode: 'employee', required: false, width: 110 },
            { key: 'location', label: '관리장소', type: 'text', required: false, width: 120 },
            { key: 'description', label: '상세설명', type: 'textarea', required: false, width: 200 },
            { key: 'sort_order', label: '정렬순서', type: 'number', required: false, width: 80 },
            { key: 'status', label: '사용상태', type: 'select', required: true, width: 80,
              options: ['사용','정지'], default: '사용' },
            { key: 'remarks', label: '비고', type: 'textarea', required: false, width: 150 },
        ],
        listColumns: ['todo_code_id','todo_name_kr','todo_category','todo_subcategory','management_cycle','assigned_employee_id','status'],
    },
};
